### ISSUE TITLE
cannot compile: undefined reference to `crypt'

### ISSUE THREAD

**Issue by pauledd** [magnue/indi_wiringpi_gpio#3]
Hi @magnue 
I just changed from gentoo to a fresh Ubuntu Mate in my RPi2 but now I am not able to compile 
indi_wiringpi_gpio anymore. I followed exactly you instructions but sudo make install failes with:

```
...
[ 83%] Building CXX object CMakeFiles/indi_wiringpi_gpio.dir/wiringpi_gpio/wiringpi_updater.cpp.o
[100%] Linking CXX executable indi_wiringpi_gpio
/usr/local/lib/libwiringPi.so: undefined reference to `crypt'
collect2: error: ld returned 1 exit status
CMakeFiles/indi_wiringpi_gpio.dir/build.make:200: recipe for target 'indi_wiringpi_gpio' failed
make[2]: *** [indi_wiringpi_gpio] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/indi_wiringpi_gpio.dir/all' failed
make[1]: *** [CMakeFiles/indi_wiringpi_gpio.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
any ideas what might be wrong with wiringPi?

**Comment by pauledd** [comment]
Someone says:
https://stackoverflow.com/a/30424785
it has to be compiled with "-L" flag but I have no clue how to implement this in this cmake thing...

**Comment by pauledd** [comment]
problem solved somehow by adding "crypt" to this line in CMakeLists.txt
`target_link_libraries(indi_wiringpi_gpio ${INDI_DRIVER_LIBRARIES} ${WIRING_PI_LIBRARIES} crypt)`

It compiles now fine but sadly I hit my prevous issue #1 again. I think there is something totally broken with indi_wiringpi_gpio and I consider to change my hardware to use usb relay.

**Comment by pauledd** [comment]
issue #1 solved again by doing my stupid fix from here:
http://indilib.org/forum/embedded-indi/2477-help-on-indi-wiringpi-gpio-crash.html?start=12#18546
I somehow forgot to apply this fix into my fork of this repo...
I stay with indi_wiringpi_gpio if no further problems pop up...
closed...

**Comment by magnue** [comment]
Isuue fixed in commit https://github.com/magnue/indi_wiringpi_gpio/commit/89bb502490de66191f53a509c6561a38f33c741a
